### ISSUE TITLE
Error while creating hub

### ISSUE THREAD

**Issue by Xyzjesus** [KompleTeam/komple-playground#17]
GM cryptans, I have an issue while creating a hub: the error is about I have no tokens on address, but I have some juno or should I have another tokens? Or do I need more Juno or stJuno?
Thanks a lot for answer
<img width="314" alt="Screenshot 2023-04-03 at 20 48 35" src="https://user-images.githubusercontent.com/62913761/229575265-79d2ad0e-5af0-47c1-a52c-f5300ef6f022.png">

**Comment by findolor** [comment]
@Xyzjesus GM sir, you are getting this error because this address does not have any junox in it. You can request the testnet tokens in the Juno discord and come back to creating the hub.
It should work when you have some tokens in it

**Comment by Xyzjesus** [comment]
@findolor gm, thanks a lot bro, i've done it with discord
